-- Drop database if it exists
DROP DATABASE IF EXISTS prestigeparfume;

-- Create the database
CREATE DATABASE prestigeparfume;
USE prestigeparfume;

-- Create table for Brands
CREATE TABLE Brand (
    brand_id INT PRIMARY KEY AUTO_INCREMENT,
    brand_name VARCHAR(255) NOT NULL
);

-- Create table for Perfumes
CREATE TABLE Perfume (
    perfume_id INT PRIMARY KEY AUTO_INCREMENT,
    perfume_name VARCHAR(255) NOT NULL,
    brand_id INT,
    lenglevity VARCHAR(100),
    sillage VARCHAR(100),
    FOREIGN KEY (brand_id) REFERENCES Brand(brand_id)
);

-- Create table for Main Accords
CREATE TABLE Main_Accords (
    accord_id INT PRIMARY KEY AUTO_INCREMENT,
    accord_name VARCHAR(255) NOT NULL
);

-- Create table for Notes
CREATE TABLE Notes (
    note_id INT PRIMARY KEY AUTO_INCREMENT,
    note_name VARCHAR(255) NOT NULL
);

-- Create linking table for Perfumes and Main Accords (Many-to-Many relationship)
CREATE TABLE Perfume_Accords (
    perfume_id INT,
    accord_id INT,
    PRIMARY KEY (perfume_id, accord_id),
    FOREIGN KEY (perfume_id) REFERENCES Perfume(perfume_id),
    FOREIGN KEY (accord_id) REFERENCES Main_Accords(accord_id)
);

-- Create linking table for Perfumes and Notes (Many-to-Many relationship)
CREATE TABLE Perfume_Notes (
    perfume_id INT,
    note_id INT,
    PRIMARY KEY (perfume_id, note_id),
    FOREIGN KEY (perfume_id) REFERENCES Perfume(perfume_id),
    FOREIGN KEY (note_id) REFERENCES Notes(note_id)
);

-- Insert brands into the Brand table
INSERT INTO Brand (brand_name) VALUES
('Acqua di Parma'),
('Bvlgari'),
('Burberry'),
('Carolina Herrera'),
('Chanel'),
('Dolce & Gabbana'),
('Geogeo Armani'),
('Hugo Boss'),
('JPG'),
('Lancome'),
('Lataffa'),
('Mancera'),
('Parfums de Marly'),
('Tom Ford'),
('Valentino'),
('Xerjoff'),
('YSL');

-- Insert perfumes into the Perfume table for Acqua di Parma
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Acqua di Parma Colonia', 1, NULL, NULL),
('Acqua di Parma Colonia Assoluta', 1, NULL, NULL),
('Acqua di Parma Colonia Assoluta Edizione Riviera', 1, NULL, NULL),
('Acqua di Parma Colonia Assoluta Edizione Speciale 2011', 1, NULL, NULL),
('Acqua di Parma Colonia Designer Edition', 1, NULL, NULL),
('Acqua di Parma Colonia Edizione Centenario', 1, NULL, NULL),
('Acqua di Parma Gelsomino Nobile', 1, NULL, NULL),
('Acqua di Parma Iris Nobile', 1, NULL, NULL),
('Acqua di Parma Iris Nobile Edizione Speciale 2008', 1, NULL, NULL),
('Acqua di Parma Magnolia Nobile', 1, NULL, NULL),
('Acqua di Parma Magnolia Nobile Special Edition', 1, NULL, NULL),
('Acqua di Parma Profumo', 1, NULL, NULL),
('Acqua di Parma Profumo 2008', 1, NULL, NULL),
('Colonia Assoluta Edizione Speciale 2013', 1, NULL, NULL),
('Colonia Assoluta In Villa', 1, NULL, NULL),
('Colonia Club', 1, NULL, NULL),
('Colonia Essenza Special Edition 2015', 1, NULL, NULL),
('Colonia Intensa', 1, NULL, NULL),
('Essenza di Colonia', 1, NULL, NULL),
('Gelsomino Nobile Edizione Speciale', 1, NULL, NULL),
('Iris Nobile 10th Anniversary Special Edition', 1, NULL, NULL),
('Iris Nobile Edizione Speziale', 1, NULL, NULL),
('Iris Nobile Sublime', 1, NULL, NULL),
('Magnolia Nobile Special Edition', 1, NULL, NULL),
('Magnolia Nobile Special Edition 2016', 1, NULL, NULL),
('Peonia Nobile', 1, NULL, NULL),
('Profumo Eau de Parfum', 1, NULL, NULL),
('Rosa Nobile', 1, NULL, NULL),
('Rosa Nobile Edizione Speciale', 1, NULL, NULL),
('Acqua Nobile Gelsomino', 1, NULL, NULL),
('Acqua Nobile Iris', 1, NULL, NULL),
('Acqua Nobile Magnolia', 1, NULL, NULL),
('Acqua Nobile Rosa', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Arancia di Capri', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Cipresso di Toscana', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Fico di Amalfi', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Ginepro di Sardegna', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Mandorlo di Sicilia', 1, NULL, NULL),
('Acqua di Parma Blu Mediterraneo Bergamotto di Calabria', 1, NULL, NULL),
('Acqua di parma Blue Mediterraneo Mirto di Panarea', 1, NULL, NULL),
('Blu Mediterraneo Foglie di Basilico', 1, NULL, NULL),
('Blu Mediterraneo Quercia Marina', 1, NULL, NULL),
('Cedro di Taormina', 1, NULL, NULL),
('Colonia Ambra', 1, NULL, NULL),
('Colonia Intensa Oud Eau de Cologne Concentree', 1, NULL, NULL),
('Colonia Leather Eau de Cologne Concentr e', 1, NULL, NULL),
('Colonia Oud', 1, NULL, NULL),
('Colonia Quercia', 1, NULL, NULL),
('Colonia Sandalo Concentr e', 1, NULL, NULL),
('Note di Colonia I', 1, NULL, NULL),
('Note di Colonia II', 1, NULL, NULL),
('Note di Colonia III', 1, NULL, NULL);

-- Insert perfumes into the Perfume table for Burberry
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Burberry Men', 2, NULL, NULL),
('Burberry Summer', 2, NULL, NULL),
('Burberry Summer for Men', 2, NULL, NULL),
('Burberry Summer for Men 2010', 2, NULL, NULL),
('Burberry Summer for Men 2011', 2, NULL, NULL),
('Burberry Summer for Men 2013', 2, NULL, NULL),
('Burberry Summer for Women 2010', 2, NULL, NULL),
('Burberry Summer for Women 2011', 2, NULL, NULL),
('Burberry Summer for Women 2013', 2, NULL, NULL),
('Burberry Summer Men 2009', 2, NULL, NULL),
('Burberry Summer Women 2009', 2, NULL, NULL),
('Burberry Women', 2, NULL, NULL),
('Burberry s for Men', 2, NULL, NULL),
('Burberrys', 2, NULL, NULL),
('Body', 2, NULL, NULL),
('Body Crystal Baccarat', 2, NULL, NULL),
('Body Eau de Parfum Intense', 2, NULL, NULL),
('Body Eau de Toilette', 2, NULL, NULL),
('Body Tender', 2, NULL, NULL),
('Burberry Body Gold Limited Edition', 2, NULL, NULL),
('Burberry Body Rose Gold', 2, NULL, NULL),
('Brit Rhythm for Her Floral', 2, NULL, NULL),
('Brit Rhythm for Him Intense', 2, NULL, NULL),
('Burberry Brit', 2, NULL, NULL),
('Burberry Brit Eau de Toilette', 2, NULL, NULL),
('Burberry Brit for Men', 2, NULL, NULL),
('Burberry Brit Gold', 2, NULL, NULL),
('Burberry Brit New Year Edition Pour Femme', 2, NULL, NULL),
('Burberry Brit New Year Edition Pour Homme', 2, NULL, NULL),
('Burberry Brit Red', 2, NULL, NULL),
('Burberry Brit Rhythm', 2, NULL, NULL),
('Burberry Brit Rhythm for Women', 2, NULL, NULL),
('Burberry Brit Sheer', 2, NULL, NULL),
('Burberry Brit Sheer 2015', 2, NULL, NULL),
('Burberry Brit Splash for Men', 2, NULL, NULL),
('Burberry Brit Summer for Men', 2, NULL, NULL),
('Burberry Brit Summer for Women', 2, NULL, NULL),
('Burberry London for Men Special Edition 2009', 2, NULL, NULL),
('Burberry London for Women Special Edition 2009', 2, NULL, NULL),
('Burberry London Special Edition for Men', 2, NULL, NULL),
('Burberry London Special Edition for Women', 2, NULL, NULL),
('London', 2, NULL, NULL),
('London for Men', 2, NULL, NULL),
('Mr Burberry', 2, NULL, NULL),
('My Burberry', 2, NULL, NULL),
('My Burberry Black', 2, NULL, NULL),
('My Burberry Eau de Toilette', 2, NULL, NULL),
('My Burberry Festive Eau de Parfum', 2, NULL, NULL),
('My Burberry Limited Edition', 2, NULL, NULL),
('Society', 2, NULL, NULL),
('Burberry Sport for Men', 2, NULL, NULL),
('Burberry Sport for Women', 2, NULL, NULL),
('Burberry Sport Ice', 2, NULL, NULL),
('Burberry Sport Ice for Men', 2, NULL, NULL),
('The Beat', 2, NULL, NULL),
('The Beat EDT', 2, NULL, NULL),
('The Beat for Men', 2, NULL, NULL),
('The Beat Intense Elixir', 2, NULL, NULL),
('Baby Touch', 2, NULL, NULL),
('Tender Touch', 2, NULL, NULL),
('Touch for Men', 2, NULL, NULL),
('Touch for Women', 2, NULL, NULL),
('Weekend for Men', 2, NULL, NULL),
('Weekend for Women', 2, NULL, NULL);

-- Insert perfumes into the Perfume table for Bvlgari
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Black', 3, NULL, NULL),
('BLV', 3, NULL, NULL),
('BLV Absolute', 3, NULL, NULL),
('BLV Eau de Parfum II', 3, NULL, NULL),
('BLV Eau d Ete', 3, NULL, NULL),
('BLV Notte Pour Femme', 3, NULL, NULL),
('BLV Notte Pour Homme', 3, NULL, NULL),
('BLV Pour Homme', 3, NULL, NULL),
('Bvlgari Extreme', 3, NULL, NULL),
('Bvlgari Pour Femme', 3, NULL, NULL),
('Bvlgari Pour Homme', 3, NULL, NULL),
('Bvlgari Pour Homme Soir', 3, NULL, NULL),
('Bvlgari Rose Essentielle Eau De Toilette Rosee', 3, NULL, NULL),
('Eau Fraiche', 3, NULL, NULL),
('Jasmin Noir', 3, NULL, NULL),
('Jasmin Noir Eau de Toilette', 3, NULL, NULL),
('Jasmin Noir L Elixir Eau de Parfum', 3, NULL, NULL),
('Jasmin Noir L Essence', 3, NULL, NULL),
('Mon Jasmin Noir', 3, NULL, NULL),
('Mon Jasmin Noir L Eau Exquise', 3, NULL, NULL),
('Mon Jasmin Noir L Elixir Eau de Parfum', 3, NULL, NULL),
('Opera Prima', 3, NULL, NULL),
('Petits et Mamans', 3, NULL, NULL),
('Rose Essentielle', 3, NULL, NULL),
('Voile de Jasmin', 3, NULL, NULL),
('Aqua Pour Homme Edition Limitee', 3, NULL, NULL),
('Aqva Amara', 3, NULL, NULL),
('Aqva Divina', 3, NULL, NULL),
('Aqva Pour Homme', 3, NULL, NULL),
('Aqva Pour Homme Atlantiqve', 3, NULL, NULL),
('Aqva Pour Homme Marine', 3, NULL, NULL),
('Aqva Pour Homme Marine Toniq', 3, NULL, NULL),
('Aqva Pour Homme Toniq', 3, NULL, NULL),
('Bvlgari Eau Parfumee au The Vert Extreme', 3, NULL, NULL),
('Eau Parfumee au The Blanc', 3, NULL, NULL),
('Eau Parfumee au The Bleu', 3, NULL, NULL),
('Eau Parfumee au The Noir', 3, NULL, NULL),
('Eau Parfumee au The Rouge', 3, NULL, NULL),
('Eau Parfumee au The Vert', 3, NULL, NULL),
('Bvlgari Man', 3, NULL, NULL),
('Bvlgari Man Black Cologne', 3, NULL, NULL),
('Bvlgari Man Black Orient', 3, NULL, NULL),
('Bvlgari Man Extreme', 3, NULL, NULL),
('Bvlgari Man Extr me All Black Editions', 3, NULL, NULL),
('Bvlgari Man In Black', 3, NULL, NULL),
('Bvlgari Man in Black All Black Edition', 3, NULL, NULL),
('Bvlgari Man The Silver Limited Edition', 3, NULL, NULL),
('Goldea', 3, NULL, NULL),
('Rose Goldea', 3, NULL, NULL),
('Amarena', 3, NULL, NULL),
('Ashlemah', 3, NULL, NULL),
('Calaluna', 3, NULL, NULL),
('Lilaia', 3, NULL, NULL),
('Maravilla', 3, NULL, NULL),
('Noorah', 3, NULL, NULL),
('Desiria', 3, NULL, NULL),
('Irinia', 3, NULL, NULL),
('Splendia', 3, NULL, NULL),
('Ambero', 3, NULL, NULL),
('Garanat', 3, NULL, NULL),
('Gyan', 3, NULL, NULL),
('Malakeos', 3, NULL, NULL),
('Onekh', 3, NULL, NULL),
('Tygar', 3, NULL, NULL),
('Lazulia', 3, NULL, NULL),
('Selima', 3, NULL, NULL),
('Zahira', 3, NULL, NULL),
('Omnia', 3, NULL, NULL),
('Omnia Amethyste', 3, NULL, NULL),
('Omnia Coral', 3, NULL, NULL),
('Omnia Crystalline', 3, NULL, NULL),
('Omnia Crystalline Eau de Parfum', 3, NULL, NULL),
('Omnia Green Jade', 3, NULL, NULL),
('Omnia Indian Garnet', 3, NULL, NULL),
('Omnia Paraiba', 3, NULL, NULL);

-- Insert perfumes into the Perfume table for Carolina Herrera
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('AquaFlore', 4, NULL, NULL),
('Carolina', 4, NULL, NULL),
('Carolina Herrera', 4, NULL, NULL),
('Flore', 4, NULL, NULL),
('Good Girl', 4, NULL, NULL),
('Herrera Aqua', 4, NULL, NULL),
('212', 4, NULL, NULL),
('212 a Summer on Ice 2003', 4, NULL, NULL),
('212 Glam', 4, NULL, NULL),
('212 Glam Men', 4, NULL, NULL),
('212 H2O', 4, NULL, NULL),
('212 H2O Men', 4, NULL, NULL),
('212 Ice', 4, NULL, NULL),
('212 Men', 4, NULL, NULL),
('212 Men a Summer on Ice 2003', 4, NULL, NULL),
('212 Men Ice', 4, NULL, NULL),
('212 Men NYC Body Spray', 4, NULL, NULL),
('212 Men on Ice 2004', 4, NULL, NULL),
('212 Men on Ice 2005', 4, NULL, NULL),
('212 Men on Ice 2006', 4, NULL, NULL),
('212 Men On Ice 2009', 4, NULL, NULL),
('212 Men Pop', 4, NULL, NULL),
('212 Men Shiny Silver', 4, NULL, NULL),
('212 Men Silver', 4, NULL, NULL),
('212 Men Splash', 4, NULL, NULL),
('212 Men Splash 2008', 4, NULL, NULL),
('212 Men Summer', 4, NULL, NULL),
('212 Men White', 4, NULL, NULL),
('212 NYC Body Spray', 4, NULL, NULL),
('212 on Ice 2004', 4, NULL, NULL),
('212 on Ice 2005', 4, NULL, NULL),
('212 on Ice 2006', 4, NULL, NULL),
('212 On Ice 2009', 4, NULL, NULL),
('212 Pop', 4, NULL, NULL),
('212 Sexy', 4, NULL, NULL),
('212 Sexy Men', 4, NULL, NULL),
('212 Shiny Silver', 4, NULL, NULL),
('212 Silver', 4, NULL, NULL),
('212 Splash 2008', 4, NULL, NULL),
('212 Splash for Women', 4, NULL, NULL),
('212 Summer', 4, NULL, NULL),
('212 Summer Cocktail', 4, NULL, NULL),
('212 Surf for Her', 4, NULL, NULL),
('212 Surf for Him', 4, NULL, NULL),
('212 White', 4, NULL, NULL),
('212 NYC Men Pills', 4, NULL, NULL),
('212 NYC Pills', 4, NULL, NULL),
('212 Sexy Men Pills', 4, NULL, NULL),
('212 Sexy Pills', 4, NULL, NULL),
('212 VIP MEN Pills', 4, NULL, NULL),
('212 VIP Pills', 4, NULL, NULL),
('212 VIP Rose Pills', 4, NULL, NULL),
('212 VIP', 4, NULL, NULL),
('212 VIP Club Edition', 4, NULL, NULL),
('212 VIP Men', 4, NULL, NULL),
('212 VIP Men Wild Party', 4, NULL, NULL),
('212 VIP Ros', 4, NULL, NULL),
('212 VIP Wild Party', 4, NULL, NULL),
('VIP Men Club Edition', 4, NULL, NULL),
('CH', 4, NULL, NULL),
('CH 2015', 4, NULL, NULL),
('CH Africa', 4, NULL, NULL),
('CH Central Park', 4, NULL, NULL),
('CH Eau De Parfum Sublime', 4, NULL, NULL),
('CH Garden Party', 4, NULL, NULL),
('CH Grand Tour', 4, NULL, NULL),
('CH L Eau', 4, NULL, NULL),
('CH Marine', 4, NULL, NULL),
('CH Men', 4, NULL, NULL),
('CH Men Africa', 4, NULL, NULL),
('CH Men Central Park', 4, NULL, NULL),
('CH Men Grand Tour', 4, NULL, NULL),
('CH Men Prive', 4, NULL, NULL),
('CH Men Sport', 4, NULL, NULL),
('CH Pink Limited Edition Love', 4, NULL, NULL),
('CH Red Gold', 4, NULL, NULL),
('Chic', 4, NULL, NULL),
('Chic For Men', 4, NULL, NULL),
('Chic Limited Red Edition', 4, NULL, NULL),
('Crystal Chic', 4, NULL, NULL),
('So Chic Limited Edition', 4, NULL, NULL),
('Amber Desire', 4, NULL, NULL),
('Burning Rose', 4, NULL, NULL),
('Carolina Herrera', 4, NULL, NULL),
('Herrera Tuberose', 4, NULL, NULL),
('Mystery Tobacco', 4, NULL, NULL),
('Neroli Boheme', 4, NULL, NULL),
('Nightfall Patchouli', 4, NULL, NULL),
('Oud Couture', 4, NULL, NULL),
('Pure Oil Of Musk', 4, NULL, NULL),
('Pure Oil Of Oud', 4, NULL, NULL),
('Pure Oil Of Rose', 4, NULL, NULL),
('Pure Oil of Sandalwood', 4, NULL, NULL),
('Herrera For Men', 4, NULL, NULL),
('Herrera for Men Refreshing Ginger', 4, NULL, NULL),
('Herrera for Men Sensual Vetiver', 4, NULL, NULL);

-- Insert perfumes into the Perfume table for Chanel
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Allure Parfum', 5, NULL, NULL),
('Antaeus', 5, NULL, NULL),
('Bois Noir', 5, NULL, NULL),
('Chanel No 46', 5, NULL, NULL),
('Une Fleur de Chanel', 5, NULL, NULL),
('Allure', 5, NULL, NULL),
('Allure eau de parfum', 5, NULL, NULL),
('Allure Eau Fraichissante Pour l Ete', 5, NULL, NULL),
('Allure Homme Eau Fraichissante Pour l Ete', 5, NULL, NULL),
('Allure Homme Edition Blanche', 5, NULL, NULL),
('Allure Homme Edition Blanche Eau de Parfum', 5, NULL, NULL),
('Allure Homme Sport', 5, NULL, NULL),
('Allure Homme Sport Cologne Sport', 5, NULL, NULL),
('Allure Homme Sport Eau Extreme', 5, NULL, NULL),
('Allure Pour Homme', 5, NULL, NULL),
('Allure Sensuelle', 5, NULL, NULL),
('Allure Sensuelle Eau de Toilette', 5, NULL, NULL),
('Allure Sensuelle Parfum', 5, NULL, NULL),
('Bleu de Chanel', 5, NULL, NULL),
('Bleu de Chanel Eau de Parfum', 5, NULL, NULL),
('Chance Eau de Parfum', 5, NULL, NULL),
('Chance Eau de Toilette', 5, NULL, NULL),
('Chance Eau Fraiche', 5, NULL, NULL),
('Chance Eau Tendre', 5, NULL, NULL),
('Chance Eau Vive', 5, NULL, NULL),
('Chance Parfum', 5, NULL, NULL),
('Chanel No 19 Eau de Parfum', 5, NULL, NULL),
('Chanel No 19 Parfum', 5, NULL, NULL),
('Chanel No 19 Poudre', 5, NULL, NULL),
('Chanel N 19', 5, NULL, NULL),
('Chanel No 5 Eau de Cologne', 5, NULL, NULL),
('Chanel No 5 Eau de Parfum', 5, NULL, NULL),
('Chanel No 5 Eau de Toilette', 5, NULL, NULL),
('Chanel No 5 Eau Premiere 2015', 5, NULL, NULL),
('Chanel No 5 L Eau', 5, NULL, NULL),
('Chanel No 5 Parfum', 5, NULL, NULL),
('Chanel N 5', 5, NULL, NULL),
('Chanel N 5 Eau Premiere', 5, NULL, NULL),
('Chanel N 5 Elixir Sensuel', 5, NULL, NULL),
('Coco Eau de Parfum', 5, NULL, NULL),
('Coco Eau de Toilette', 5, NULL, NULL),
('Coco Mademoiselle', 5, NULL, NULL),
('Coco Mademoiselle Eau de toilette', 5, NULL, NULL),
('Coco Mademoiselle L Extrait', 5, NULL, NULL),
('Coco Mademoiselle Parfum', 5, NULL, NULL),
('Coco Noir', 5, NULL, NULL),
('Coco Noir Extrait', 5, NULL, NULL),
('Coco Parfum', 5, NULL, NULL),
('Cristalle Eau de Parfum', 5, NULL, NULL),
('Cristalle Eau de Toilette', 5, NULL, NULL),
('Cristalle Eau Verte', 5, NULL, NULL),
('Egoiste', 5, NULL, NULL),
('Egoiste Cologne Concentree', 5, NULL, NULL),
('Egoiste Platinum', 5, NULL, NULL),
('1932 Eau de Parfum', 5, NULL, NULL),
('31 Rue Cambon Eau de Parfum', 5, NULL, NULL),
('Beige Eau de Parfum', 5, NULL, NULL),
('Bel Respiro Eau de Parfum', 5, NULL, NULL),
('Bois des Iles', 5, NULL, NULL),
('Bois des Iles Eau de Parfum', 5, NULL, NULL),
('Boy Chanel', 5, NULL, NULL),
('Chanel N 22', 5, NULL, NULL),
('Coromandel Eau de Parfum', 5, NULL, NULL),
('Cuir de Russie', 5, NULL, NULL),
('Cuir de Russie Eau de Parfum', 5, NULL, NULL),
('Gardenia', 5, NULL, NULL),
('Gardenia Eau de Parfum', 5, NULL, NULL),
('Jersey Eau de Parfum', 5, NULL, NULL),
('La Pausa Eau de Parfum', 5, NULL, NULL),
('Les Exclusifs de Chanel 1932', 5, NULL, NULL),
('Les Exclusifs de Chanel 1932 Parfum', 5, NULL, NULL),
('Les Exclusifs de Chanel 28 La Pausa', 5, NULL, NULL),
('Les Exclusifs de Chanel 31 Rue Cambon', 5, NULL, NULL),
('Les Exclusifs de Chanel Beige', 5, NULL, NULL),
('Les Exclusifs de Chanel Beige Parfum', 5, NULL, NULL),
('Les Exclusifs de Chanel Bel Respiro', 5, NULL, NULL),
('Les Exclusifs de Chanel Coromandel', 5, NULL, NULL),
('Les Exclusifs de Chanel Cuir de Russie', 5, NULL, NULL),
('Les Exclusifs de Chanel Eau de Cologne', 5, NULL, NULL),
('Les Exclusifs de Chanel Jersey', 5, NULL, NULL),
('Les Exclusifs de Chanel Jersey Parfum', 5, NULL, NULL),
('Les Exclusifs de Chanel Misia', 5, NULL, NULL),
('Les Exclusifs de Chanel No 18', 5, NULL, NULL),
('Les Exclusifs de Chanel No 22', 5, NULL, NULL),
('Les Exclusifs de Chanel Sycomore', 5, NULL, NULL),
('Misia Eau de Parfum', 5, NULL, NULL),
('No 18 Eau de Parfum', 5, NULL, NULL),
('No 22 Eau de Parfum', 5, NULL, NULL),
('Sycomore Eau de Parfum', 5, NULL, NULL),
('Pour Monsieur', 5, NULL, NULL),
('Pour Monsieur Concentree', 5, NULL, NULL),
('Pour Monsieur Eau de Parfum', 5, NULL, NULL);

-- Insert perfumes into the Perfume table for Dolce & Gabbana
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Sicily', 6, NULL, NULL),
('By', 6, NULL, NULL),
('Dolce Gabbana Perfume for Babies', 6, NULL, NULL),
('Dolce Gabbana Pour Femme', 6, NULL, NULL),
('Dolce Gabbana Pour Femme Intense', 6, NULL, NULL),
('Dolce Gabbana Pour Homme', 6, NULL, NULL),
('Dolce Gabbana Pour Homme Intenso', 6, NULL, NULL),
('D G Feminine', 6, NULL, NULL),
('D G Masculine', 6, NULL, NULL),
('D G Anthology L Empereur 4', 6, NULL, NULL),
('D G Anthology La Force 11', 6, NULL, NULL),
('D G Anthology La Lune 18', 6, NULL, NULL),
('D G Anthology La Roue de La Fortune 10', 6, NULL, NULL),
('D G Anthology La Temperance 14', 6, NULL, NULL),
('D G Anthology Le Bateleur 1', 6, NULL, NULL),
('D G Anthology Le Fou 21', 6, NULL, NULL),
('D G Anthology L Amoureux 6', 6, NULL, NULL),
('D G Anthology L Imperatrice 3', 6, NULL, NULL),
('Dolce', 6, NULL, NULL),
('Dolce Floral Drops', 6, NULL, NULL),
('Dolce Rosa Excelsa', 6, NULL, NULL),
('D G Light Blue', 6, NULL, NULL),
('Light Blue Discover Vulcano Pour Homme', 6, NULL, NULL),
('Light Blue Dreaming in Portofino', 6, NULL, NULL),
('Light Blue Escape to Panarea', 6, NULL, NULL),
('Light Blue Living Stromboli', 6, NULL, NULL),
('Light Blue Love in Capri', 6, NULL, NULL),
('Light Blue pour Homme', 6, NULL, NULL),
('Light Blue Pour Homme Beauty of Capri', 6, NULL, NULL),
('Light Blue Sunset in Salina', 6, NULL, NULL),
('Light Blue Swimming in Lipari', 6, NULL, NULL),
('L eau The One', 6, NULL, NULL),
('Rose The One', 6, NULL, NULL),
('The One', 6, NULL, NULL),
('The One Collector For Men', 6, NULL, NULL),
('The One Collector For Women', 6, NULL, NULL),
('The One Desire', 6, NULL, NULL),
('The One Essence', 6, NULL, NULL),
('The One for Men', 6, NULL, NULL),
('The One for Men Eau de Parfum', 6, NULL, NULL),
('The One for Men Platinum Limited Edition', 6, NULL, NULL),
('The One Gentleman', 6, NULL, NULL),
('The One Gold Limited Edition', 6, NULL, NULL),
('The One Lace Edition', 6, NULL, NULL),
('The One Royal Night', 6, NULL, NULL),
('The One Sport', 6, NULL, NULL),
('Velvet Bergamot', 6, NULL, NULL),
('Velvet Cypress', 6, NULL, NULL),
('Velvet Desert Oud', 6, NULL, NULL),
('Velvet Desire', 6, NULL, NULL),
('Velvet Exotic Leather', 6, NULL, NULL),
('Velvet Ginestra', 6, NULL, NULL),
('Velvet Love', 6, NULL, NULL),
('Velvet Mimosa Bloom', 6, NULL, NULL),
('Velvet Patchouli', 6, NULL, NULL),
('Velvet Pure', 6, NULL, NULL),
('Velvet Rose', 6, NULL, NULL),
('Velvet Sublime', 6, NULL, NULL),
('Velvet Tender Oud', 6, NULL, NULL),
('Velvet Vetiver', 6, NULL, NULL),
('Velvet Wood', 6, NULL, NULL);

-- Insert perfumes into the Perfume table for Giorgio Armani
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Gio', 7, NULL, NULL),
('Acqua di Gio', 7, NULL, NULL),
('Acqua di Gio Blue Edition Pour Homme', 7, NULL, NULL),
('Acqua di Gio Essenza', 7, NULL, NULL),
('Acqua di Gio Profumo', 7, NULL, NULL),
('Aqua di Gio Aqua di Life Edition', 7, NULL, NULL),
('Acqua di Gioia', 7, NULL, NULL),
('Acqua di Gioia Eau de Parfum Satinee', 7, NULL, NULL),
('Acqua di Gioia Eau de Toilette', 7, NULL, NULL),
('Acqua Di Gioia Eau Fraiche', 7, NULL, NULL),
('Acqua di Gioia Essenza', 7, NULL, NULL),
('Acqua Di Gioia Jasmine', 7, NULL, NULL),
('Air di Gioia', 7, NULL, NULL),
('Sun di Gioia', 7, NULL, NULL),
('Armani Attitude', 7, NULL, NULL),
('Attitude Extreme', 7, NULL, NULL),
('Armani Code', 7, NULL, NULL),
('Armani Code Cashmere', 7, NULL, NULL),
('Armani Code Casino Limited Edition 2008', 7, NULL, NULL),
('Armani Code Colonia', 7, NULL, NULL),
('Armani Code Couture Edition', 7, NULL, NULL),
('Armani Code Elixir', 7, NULL, NULL),
('Armani Code for Women', 7, NULL, NULL),
('Armani Code Golden Edition', 7, NULL, NULL),
('Armani Code Ice', 7, NULL, NULL),
('Armani Code Le Parfum', 7, NULL, NULL),
('Armani Code Luna', 7, NULL, NULL),
('Armani Code Mirror Edition', 7, NULL, NULL),
('Armani Code Profumo', 7, NULL, NULL),
('Armani Code Satin', 7, NULL, NULL),
('Armani Code Sheer', 7, NULL, NULL),
('Armani Code Special Blend', 7, NULL, NULL),
('Armani Code Sport', 7, NULL, NULL),
('Armani Code Sport Athlete', 7, NULL, NULL),
('Armani Code Sport Edition 2016', 7, NULL, NULL),
('Armani Code Summer pour Femme', 7, NULL, NULL),
('Armani Code Summer Pour Femme 2010', 7, NULL, NULL),
('Armani Code Summer Pour Femme 2011', 7, NULL, NULL),
('Armani Code Summer pour Homme', 7, NULL, NULL),
('Armani Code Summer Pour Homme 2010', 7, NULL, NULL),
('Armani Code Summer Pour Homme 2011', 7, NULL, NULL),
('Armani Code Turquoise for Men', 7, NULL, NULL),
('Armani Code Turquoise for Women', 7, NULL, NULL),
('Armani Code Ultimate', 7, NULL, NULL),
('Armani Code Ultimate Femme', 7, NULL, NULL),
('Armani Mania', 7, NULL, NULL),
('Mania', 7, NULL, NULL),
('Summer Mania Eau Fraiche pour Femme', 7, NULL, NULL),
('Summer Mania Eau Fraiche pour Homme', 7, NULL, NULL),
('Summer Mania Femme', 7, NULL, NULL),
('Summer Mania Homme', 7, NULL, NULL),
('Armani Prive Ambre Eccentrico', 7, NULL, NULL),
('Armani Priv Cologne Eclat de Jasmin', 7, NULL, NULL),
('Armani Prive Cologne Spray Ambre Soie', 7, NULL, NULL),
('Armani Prive Cologne Spray Bois d Encens', 7, NULL, NULL),
('Armani Prive Cologne Spray Cuir Amethyste', 7, NULL, NULL),
('Armani Prive Cologne Spray Eau de Jade', 7, NULL, NULL),
('Armani Prive Cologne Spray Pierre de Lune', 7, NULL, NULL),
('Armani Prive Cuir Majeste', 7, NULL, NULL),
('Armani Prive Encens Satin', 7, NULL, NULL),
('Armani Prive Figuier Eden', 7, NULL, NULL),
('Armani Prive Iris Celadon', 7, NULL, NULL),
('Armani Prive Oranger Alhambra', 7, NULL, NULL),
('Armani Prive Pivoine Suzhou', 7, NULL, NULL),
('Armani Prive Pivoine Suzhou Soie de Nacre Limited Edition', 7, NULL, NULL),
('Armani Prive Rose Alexandrie', 7, NULL, NULL),
('Armani Prive Sable Fume', 7, NULL, NULL),
('Armani Prive Sable Or', 7, NULL, NULL),
('Armani Prive Vetiver Babylone', 7, NULL, NULL),
('Cedre Olympe', 7, NULL, NULL),
('Armani Prive Fil Rouge', 7, NULL, NULL),
('Armani Prive La Femme Bleue', 7, NULL, NULL),
('Armani Priv Ombre Lumiere', 7, NULL, NULL),
('La Femme Nacre', 7, NULL, NULL),
('Nuances', 7, NULL, NULL),
('Armani Priv Ambre Orient', 7, NULL, NULL),
('Armani Priv Oud Royal', 7, NULL, NULL),
('Armani Priv Rose d Arabie', 7, NULL, NULL),
('Armani Prive Rose d Arabie L Or du Desert', 7, NULL, NULL),
('Armani Prive Rose d Arabie Limited Edition Swarovski', 7, NULL, NULL),
('Cuir Noir', 7, NULL, NULL),
('Myrrhe Imp riale', 7, NULL, NULL),
('Armani Eau de C dre', 7, NULL, NULL),
('Armani Eau de Nuit', 7, NULL, NULL),
('Armani Eau de Nuit Oud', 7, NULL, NULL),
('Armani Eau d Aromes', 7, NULL, NULL),
('Armani Eau Pour Homme', 7, NULL, NULL),
('Armani Eau Pour Homme new', 7, NULL, NULL),
('Emporio Armani City Glam for Her', 7, NULL, NULL),
('Emporio Armani City Glam for Him', 7, NULL, NULL),
('Emporio Armani For Her 2008', 7, NULL, NULL),
('Emporio Armani For Him 2008', 7, NULL, NULL),
('Emporio Armani Lei', 7, NULL, NULL),
('Emporio Armani Lui', 7, NULL, NULL),
('Emporio Armani Night', 7, NULL, NULL),
('Emporio Armani Red Pour Elle White', 7, NULL, NULL),
('Emporio Armani Red Pour Lui White', 7, NULL, NULL),
('Emporio Armani White For Her', 7, NULL, NULL),
('Emporio Armani White For Him', 7, NULL, NULL),
('Emporio Remix for Her', 7, NULL, NULL),
('Emporio Remix for Him', 7, NULL, NULL),
('Emporio Armani Diamonds', 7, NULL, NULL),
('Emporio Armani Diamonds Black Carat for Her', 7, NULL, NULL),
('Emporio Armani Diamonds Black Carat for Him', 7, NULL, NULL),
('Emporio Armani Diamonds Club', 7, NULL, NULL),
('Emporio Armani Diamonds Club for Him', 7, NULL, NULL),
('Emporio Armani Diamonds Eau de Toilette', 7, NULL, NULL),
('Emporio Armani Diamonds for Men', 7, NULL, NULL),
('Emporio Armani Diamonds for Men Summer Edition', 7, NULL, NULL),
('Emporio Armani Diamonds for Women Summer Edition', 7, NULL, NULL),
('Emporio Armani Diamonds He Limited Edition', 7, NULL, NULL),
('Emporio Armani Diamonds Intense', 7, NULL, NULL),
('Emporio Armani Diamonds Rocks', 7, NULL, NULL),
('Emporio Armani Diamonds Rose', 7, NULL, NULL),
('Emporio Armani Diamonds Summer Fraiche for Men', 7, NULL, NULL),
('Emporio Armani Diamonds Summer Fraiche for Women', 7, NULL, NULL),
('Emporio Armani Diamonds Violet', 7, NULL, NULL),
('Idole d Armani', 7, NULL, NULL),
('Idole d Armani Eau de Toilette', 7, NULL, NULL),
('Onde Extase', 7, NULL, NULL),
('Onde Mystere', 7, NULL, NULL),
('Onde Vertige', 7, NULL, NULL),
('Sensi', 7, NULL, NULL),
('Sensi Jewel', 7, NULL, NULL),
('Sensi White Notes', 7, NULL, NULL),
('Si', 7, NULL, NULL),
('Si Eau de Toilette', 7, NULL, NULL),
('Si Golden Bow', 7, NULL, NULL),
('Si Huile de Parfum', 7, NULL, NULL),
('S Intense', 7, NULL, NULL),
('Si Intense Night Light', 7, NULL, NULL),
('Si Le Parfum', 7, NULL, NULL),
('Si Night Light', 7, NULL, NULL),
('Si Rose Signature', 7, NULL, NULL),
('Si White', 7, NULL, NULL),
('Armani Prive Rouge Malachite', 7, NULL, NULL),
('Armani Prive Vert Malachite', 7, NULL, NULL);

-- Insert perfumes into the Perfume table for Hugo Boss
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Baldessarini', 8, NULL, NULL),
('Boss Intense', 8, NULL, NULL),
('Boss Intense Shimmer Edition', 8, NULL, NULL),
('Boss Number One', 8, NULL, NULL),
('Boss Pure', 8, NULL, NULL),
('Boss Selection', 8, NULL, NULL),
('Boss Soul', 8, NULL, NULL),
('Boss Spirit', 8, NULL, NULL),
('Boss Sport', 8, NULL, NULL),
('Boss Woman', 8, NULL, NULL),
('Deep Red', 8, NULL, NULL),
('Hugo Dark Blue', 8, NULL, NULL),
('Pure Purple', 8, NULL, NULL),
('Boss Bottled', 8, NULL, NULL),
('Boss Bottled Collector s Edition', 8, NULL, NULL),
('Boss Bottled Intense', 8, NULL, NULL),
('Boss Bottled Intense Eau de Parfum', 8, NULL, NULL),
('Boss Bottled Night', 8, NULL, NULL),
('Boss Bottled Oud', 8, NULL, NULL),
('Boss Bottled Sport', 8, NULL, NULL),
('Boss Bottled Unlimited', 8, NULL, NULL),
('Boss Bottled Unlimited Mats Hummels Edition', 8, NULL, NULL),
('Boss Elements', 8, NULL, NULL),
('Boss Elements Aqua', 8, NULL, NULL),
('Essence de Femme', 8, NULL, NULL),
('Femme', 8, NULL, NULL),
('Femme L Eau Fraiche', 8, NULL, NULL),
('Boss in Motion', 8, NULL, NULL),
('Boss In Motion Black', 8, NULL, NULL),
('Boss In Motion Blue', 8, NULL, NULL),
('Boss in Motion edition IV', 8, NULL, NULL),
('Boss In Motion Green', 8, NULL, NULL),
('Boss In Motion Orange Made For Summer', 8, NULL, NULL),
('Boss In Motion White', 8, NULL, NULL),
('Boss Jour Pour Femme', 8, NULL, NULL),
('Boss Jour Pour Femme Lumineuse', 8, NULL, NULL),
('Boss Ma Vie Pour Femme', 8, NULL, NULL),
('Boss Ma Vie Pour Femme Florale', 8, NULL, NULL),
('Boss Ma Vie Pour Femme Intense', 8, NULL, NULL),
('Boss Nuit Pour Femme', 8, NULL, NULL),
('Boss Nuit Pour Femme Intense', 8, NULL, NULL),
('Boss Orange', 8, NULL, NULL),
('Boss Orange Celebration of Happiness', 8, NULL, NULL),
('Boss Orange Charity Edition', 8, NULL, NULL),
('Boss Orange Eau de Parfum', 8, NULL, NULL),
('Boss Orange for Men', 8, NULL, NULL),
('Boss Orange for Men Feel Good Summer', 8, NULL, NULL),
('Boss Orange Man Charity Edition', 8, NULL, NULL),
('Boss Orange Sunset', 8, NULL, NULL),
('BOSS The Collection Cashmere Patchouli', 8, NULL, NULL),
('BOSS The Collection Cotton Verbena', 8, NULL, NULL),
('BOSS The Collection Damask Oud', 8, NULL, NULL),
('BOSS The Collection Silk Jasmine', 8, NULL, NULL),
('BOSS The Collection Velvet Amber', 8, NULL, NULL),
('BOSS The Collection Wool Musk', 8, NULL, NULL),
('Boss The Scent', 8, NULL, NULL),
('Boss The Scent For Her', 8, NULL, NULL),
('Boss Element', 8, NULL, NULL),
('Hugo', 8, NULL, NULL),
('Hugo by Karim Rashid', 8, NULL, NULL),
('Hugo Create Limited Edition', 8, NULL, NULL),
('Hugo Extreme', 8, NULL, NULL),
('Hugo Iced', 8, NULL, NULL),
('Hugo Just Different', 8, NULL, NULL),
('Hugo Red', 8, NULL, NULL),
('Hugo Spray', 8, NULL, NULL),
('Hugo Energise', 8, NULL, NULL),
('Hugo Energize Spray', 8, NULL, NULL),
('Hugo Woman', 8, NULL, NULL),
('Hugo Woman Eau de Parfum', 8, NULL, NULL),
('Hugo Woman Extreme', 8, NULL, NULL),
('Hugo XX', 8, NULL, NULL),
('Hugo XX Summer Edition', 8, NULL, NULL),
('Hugo XY', 8, NULL, NULL),
('Hugo XY Summer Edition', 8, NULL, NULL),
('Boss Jour Pour Femme Runway Edition', 8, NULL, NULL),
('Boss Ma Vie Pour Femme Runway Edition', 8, NULL, NULL),
('Boss Nuit Pour Femme Runway Edition', 8, NULL, NULL);

-- Insert perfumes into the Perfume table for Jean Paul Gaultier
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Fragile', 9, NULL, NULL),
('Fragile Eau de Toilette', 9, NULL, NULL),
('Gaultier 2', 9, NULL, NULL),
('Gaultier 2 Eau d Amour', 9, NULL, NULL),
('Jean Paul Gaultier Summer', 9, NULL, NULL),
('Kokorico', 9, NULL, NULL),
('Kokorico by Night', 9, NULL, NULL),
('Monsieur Eau du Matin', 9, NULL, NULL),
('Classique', 9, NULL, NULL),
('Classique Alcohol Free Summer Fragrance 2006', 9, NULL, NULL),
('Classique Autumn Winter', 9, NULL, NULL),
('Classique Belle en Corset', 9, NULL, NULL),
('Classique Betty Boop Eau Fraiche', 9, NULL, NULL),
('Classique Bien Roulee', 9, NULL, NULL),
('Classique Charm Edition', 9, NULL, NULL),
('Classique Collector Glam Edition', 9, NULL, NULL),
('Classique Corset Couture', 9, NULL, NULL),
('Classique Couple', 9, NULL, NULL),
('Classique Eau d Ete 2003', 9, NULL, NULL),
('Classique Eau de Parfum', 9, NULL, NULL),
('Classique Edition Collector', 9, NULL, NULL),
('Classique Essence de Parfum', 9, NULL, NULL),
('Classique Gold Collection', 9, NULL, NULL),
('Classique Intense', 9, NULL, NULL),
('Classique Intense Collector Glam Edition', 9, NULL, NULL),
('Classique La Robe Chinoise', 9, NULL, NULL),
('Classique Les d ete 2005', 9, NULL, NULL),
('Classique Limited Edition 2003', 9, NULL, NULL),
('Classique Love Actually', 9, NULL, NULL),
('Classique L Eau d Ete', 9, NULL, NULL),
('Classique L Eau d Ete Sans Alcohol', 9, NULL, NULL),
('Classique l Eau d Et 2007', 9, NULL, NULL),
('Classique Pirate Edition', 9, NULL, NULL),
('Classique Prestige', 9, NULL, NULL),
('Classique Robe Velours', 9, NULL, NULL),
('Classique Rock Star', 9, NULL, NULL),
('Classique Silver My Skin', 9, NULL, NULL),
('Classique Summer 2010', 9, NULL, NULL),
('Classique Summer 2011', 9, NULL, NULL),
('Classique Summer 2012', 9, NULL, NULL),
('Classique Summer 2013', 9, NULL, NULL),
('Classique Summer 2015', 9, NULL, NULL),
('Classique Summer Edition 2014', 9, NULL, NULL),
('Classique Summer Fragrance 2008', 9, NULL, NULL),
('Classique Summer Fragrance 2009', 9, NULL, NULL),
('Classique X', 9, NULL, NULL),
('Classique X Eau de Parfum', 9, NULL, NULL),
('Classique X Extrait', 9, NULL, NULL),
('Classique X Jewel Edition 2011', 9, NULL, NULL),
('Classique X L Eau', 9, NULL, NULL),
('Classique X Love Actually', 9, NULL, NULL),
('Cologne Le Male Summer 2008', 9, NULL, NULL),
('Fleur du M le', 9, NULL, NULL),
('La Cologne Fleur du Male', 9, NULL, NULL),
('Le Beau Male', 9, NULL, NULL),
('Le Beau Male Capitaine Collector', 9, NULL, NULL),
('Le Beau Male Edition Collector', 9, NULL, NULL),
('Le Beau Male Summer 2014', 9, NULL, NULL),
('Le Male', 9, NULL, NULL),
('Le Male Capitaine Collector', 9, NULL, NULL),
('Le Male Couple', 9, NULL, NULL),
('Le Male Eau d Ete 2004', 9, NULL, NULL),
('Le Male Edition Collector', 9, NULL, NULL),
('Le Male Essence de Parfum', 9, NULL, NULL),
('Le Male Gladiator', 9, NULL, NULL),
('Le Male Jean Paul Cool', 9, NULL, NULL),
('Le Male Kilt', 9, NULL, NULL),
('Le Male Les d Ete 2005', 9, NULL, NULL),
('Le Male Limited Edition 2009', 9, NULL, NULL),
('Le Male Love Actually', 9, NULL, NULL),
('Le Male Pin Up Collectors Edition', 9, NULL, NULL),
('Le Male Pirate Edition', 9, NULL, NULL),
('Le Male Popeye Eau Fraiche', 9, NULL, NULL),
('Le Male Scuba Diver', 9, NULL, NULL),
('Le Male Shaker Limited Edition', 9, NULL, NULL),
('Le Male Silver My Skin', 9, NULL, NULL),
('Le Male Stimulating Body Spray 2006', 9, NULL, NULL),
('Le Male Summer 2010', 9, NULL, NULL),
('Le Male Summer 2011', 9, NULL, NULL),
('Le Male Summer 2012', 9, NULL, NULL),
('Le Male Summer 2013', 9, NULL, NULL),
('Le Male Summer 2014', 9, NULL, NULL),
('Le Male Summer 2015', 9, NULL, NULL),
('Le Male Summer Fragrance 2009', 9, NULL, NULL),
('Le Male Terrible', 9, NULL, NULL),
('Le Male Terrible Shaker', 9, NULL, NULL),
('Le Male Tonique Cologne', 9, NULL, NULL),
('Ultra Male', 9, NULL, NULL),
('Ma Dame', 9, NULL, NULL),
('Ma Dame Eau de Parfum', 9, NULL, NULL),
('Ma Dame Eau Fraiche', 9, NULL, NULL),
('Ma Dame Eau Fraiche Summer 2010', 9, NULL, NULL),
('Ma Dame It', 9, NULL, NULL),
('Ma Dame Rose n Roll', 9, NULL, NULL);

-- Insert perfumes into the Perfume table for Lancôme
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('2000 Et Une Folies', 10, NULL, NULL),
('2000 et Une Nuit', 10, NULL, NULL),
('2000 et Une Rose', 10, NULL, NULL),
('Aroma Blue', 10, NULL, NULL),
('Aroma Calm', 10, NULL, NULL),
('Aroma Delice', 10, NULL, NULL),
('Aroma Fit', 10, NULL, NULL),
('Aroma Juice', 10, NULL, NULL),
('Aroma Sun', 10, NULL, NULL),
('Aroma Tonic', 10, NULL, NULL),
('Attraction', 10, NULL, NULL),
('Attraction Summer', 10, NULL, NULL),
('Balafre', 10, NULL, NULL),
('Balafre Brun', 10, NULL, NULL),
('Balafre Vert', 10, NULL, NULL),
('Benghal', 10, NULL, NULL),
('Calypso', 10, NULL, NULL),
('Chrysalide Now or Never', 10, NULL, NULL),
('Climat', 10, NULL, NULL),
('Climat L Edition Mythique', 10, NULL, NULL),
('Climat Parfum Extrait', 10, NULL, NULL),
('Connexion', 10, NULL, NULL),
('Cyclades', 10, NULL, NULL),
('Envol', 10, NULL, NULL),
('Hypnose', 10, NULL, NULL),
('Hypnose Eau Legere', 10, NULL, NULL),
('Hypnose Homme', 10, NULL, NULL),
('Hypnose Homme Cologne', 10, NULL, NULL),
('Hypnose Homme Eau Fraiche', 10, NULL, NULL),
('Hypnose Hypnotizing Elixir', 10, NULL, NULL),
('Hypnose Senses', 10, NULL, NULL),
('Joyeux t', 10, NULL, NULL),
('L Autre Oud', 10, NULL, NULL),
('Magie Noire', 10, NULL, NULL),
('Magie Noire Parfum', 10, NULL, NULL),
('Magnifique', 10, NULL, NULL),
('Magnifique Eau de Toilette', 10, NULL, NULL),
('O de Lancome', 10, NULL, NULL),
('O de L Orangerie', 10, NULL, NULL),
('O d Azur', 10, NULL, NULL),
('O Intense', 10, NULL, NULL),
('O Oui', 10, NULL, NULL),
('O pour Homme', 10, NULL, NULL),
('Oud Bouquet', 10, NULL, NULL),
('Poeme', 10, NULL, NULL),
('Programme Homme Cologne', 10, NULL, NULL),
('Reves de Singapour', 10, NULL, NULL),
('Rouge Now or Never', 10, NULL, NULL),
('Sagamore', 10, NULL, NULL),
('Sikkim Parfum', 10, NULL, NULL),
('Trophee', 10, NULL, NULL),
('Tropiques', 10, NULL, NULL),
('Jasmins Marzipane', 10, NULL, NULL),
('L Autre Oud', 10, NULL, NULL),
('Lavandes Trianon', 10, NULL, NULL),
('Oud Ambroisie', 10, NULL, NULL),
('Oud Bouquet', 10, NULL, NULL),
('Tube reuses Castane', 10, NULL, NULL),
('La Vie Est Belle', 10, NULL, NULL),
('La Vie Est Belle Christmas Edition', 10, NULL, NULL),
('La Vie Est Belle Edition Limitee', 10, NULL, NULL),
('La Vie Est Belle Glitter', 10, NULL, NULL),
('La Vie Est Belle L Eau de Parfum Intense', 10, NULL, NULL),
('La Vie Est Belle L Eau de Parfum Legere', 10, NULL, NULL),
('La Vie Est Belle L Eau de Toilette', 10, NULL, NULL),
('La Vie Est Belle L Extrait de Parfum', 10, NULL, NULL),
('La Vie Est Belle L Extrait de Parfum by Mellerio dits Meller', 10, NULL, NULL),
('La Vie Est Belle L Absolu', 10, NULL, NULL),
('La Vie Est Belle L Eau de Toilette Florale', 10, NULL, NULL),
('Balafre', 10, NULL, NULL),
('Climat', 10, NULL, NULL),
('Cuir de Lanc me', 10, NULL, NULL),
('Magie', 10, NULL, NULL),
('Mille et Une Roses', 10, NULL, NULL),
('Peut Etre La Collection Fragrances', 10, NULL, NULL),
('Sagamore', 10, NULL, NULL),
('Sikkim', 10, NULL, NULL),
('Miracle', 10, NULL, NULL),
('Miracle Blossom', 10, NULL, NULL),
('Miracle Eau Legere Sheer Fragrance', 10, NULL, NULL),
('Miracle Forever', 10, NULL, NULL),
('Miracle Homme', 10, NULL, NULL),
('Miracle Homme L Aquatonic', 10, NULL, NULL),
('Miracle Intense', 10, NULL, NULL),
('Miracle So Magic', 10, NULL, NULL),
('Miracle Summer', 10, NULL, NULL),
('Miracle Tendre Voyage', 10, NULL, NULL),
('Miracle Ultra Pink', 10, NULL, NULL),
('Miracle White Nights', 10, NULL, NULL),
('La Nuit Tresor', 10, NULL, NULL),
('La Nuit Tresor Caresse', 10, NULL, NULL),
('La Nuit Tresor Edition Limitee', 10, NULL, NULL),
('Lancome Tresor Eau Legere Sheer', 10, NULL, NULL),
('Tresor', 10, NULL, NULL),
('Tresor Diamant Noir', 10, NULL, NULL),
('Tresor Eau de Parfum Lumineuse', 10, NULL, NULL),
('Tr sor Eau de Toilette', 10, NULL, NULL),
('Tresor Edition Limitee Fete des Meres', 10, NULL, NULL),
('Tresor Elixir', 10, NULL, NULL),
('Tresor In Love', 10, NULL, NULL),
('Tresor In Love La Coquette Limited Edition', 10, NULL, NULL),
('Tresor L Absolu', 10, NULL, NULL),
('Tresor L Absolu Desir', 10, NULL, NULL),
('Tresor L Eau de Toilette', 10, NULL, NULL),
('Tresor Midnight Rose', 10, NULL, NULL),
('Tresor Midnight Rose Elixir D Orient', 10, NULL, NULL),
('Tresor Midnight Rose La Coquette Limited Edition', 10, NULL, NULL),
('Tresor Sheer Eau De Printemps', 10, NULL, NULL),
('Tresor Sheer Fragrance', 10, NULL, NULL),
('Tresor Sparkling', 10, NULL, NULL);

-- Insert perfumes into the Perfume table for Lattafa
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('24 Carat Pure Gold', 11, NULL, NULL),
('24 CARAT WHITE GOLD', 11, NULL, NULL),
('Al Azea', 11, NULL, NULL),
('Al Dur Al Maknoon Gold', 11, NULL, NULL),
('Al Dur Al Maknoon Silver', 11, NULL, NULL),
('Al Fursan', 11, NULL, NULL),
('Ameer Al Oud 2', 11, NULL, NULL),
('Ameer Al Oudh', 11, NULL, NULL),
('Amwaaj Al Oud', 11, NULL, NULL),
('Ashjan', 11, NULL, NULL),
('Attar Al Malouk', 11, NULL, NULL),
('Attri', 11, NULL, NULL),
('Attri Khusoosi', 11, NULL, NULL),
('Bint Al Sultan', 11, NULL, NULL),
('Captain', 11, NULL, NULL),
('Chic Oud', 11, NULL, NULL),
('Chic Oud Summer', 11, NULL, NULL),
('Danhal Oud Kambodi', 11, NULL, NULL),
('Dehn Al Oud Al Ameeri', 11, NULL, NULL),
('Fakhar Lattafa', 11, NULL, NULL),
('Ghadeer', 11, NULL, NULL),
('Just Oud', 11, NULL, NULL),
('Just Oud Boulevard', 11, NULL, NULL),
('Khalis Musk Pure Musk', 11, NULL, NULL),
('Khalis Oudi Pure Oudi', 11, NULL, NULL),
('Khurafi', 11, NULL, NULL),
('Laitak Ma e', 11, NULL, NULL),
('Lubb Al Oud', 11, NULL, NULL),
('Lubb Al Warad', 11, NULL, NULL),
('Mahasin Crystal', 11, NULL, NULL),
('Mahasin Crystal Banafsaj', 11, NULL, NULL),
('Muftah Al Quloob', 11, NULL, NULL),
('Mukhallat Oudi', 11, NULL, NULL),
('Musk Al Ghazal', 11, NULL, NULL),
('Musk Andalusi', 11, NULL, NULL),
('Nafeas', 11, NULL, NULL),
('Nakahat Al Oud', 11, NULL, NULL),
('Night Oud', 11, NULL, NULL),
('Oud Salama', 11, NULL, NULL),
('Raghba', 11, NULL, NULL),
('Raghba Classic', 11, NULL, NULL),
('Raghba Muski', 11, NULL, NULL),
('Raghba Wood Intense', 11, NULL, NULL),
('Rooh Al Banat', 11, NULL, NULL),
('Rooh Al Shabab', 11, NULL, NULL),
('Royal Highness Gold', 11, NULL, NULL),
('Royal Highness Silver', 11, NULL, NULL),
('Samaha', 11, NULL, NULL),
('Seher Al Gharam', 11, NULL, NULL),
('Ser Al Khulood', 11, NULL, NULL),
('Shahariyaar', 11, NULL, NULL),
('Shahrazad', 11, NULL, NULL),
('Sheikh Al Shuyukh', 11, NULL, NULL),
('Sheikh Al Shuyukh Luxe Edition', 11, NULL, NULL),
('Sheikh Shuyukh Khusoosi', 11, NULL, NULL),
('Shurooq Al Hind', 11, NULL, NULL),
('Ta abee', 11, NULL, NULL),
('Taj Rasi Gold Edition', 11, NULL, NULL),
('Taj Rasi Silver Edition', 11, NULL, NULL),
('Tamayuz Lattafa', 11, NULL, NULL),
('Washwasha', 11, NULL, NULL),
('Hind Al Sultan', 11, NULL, NULL),
('Oud Al Mamlikah', 11, NULL, NULL),
('Safwat Al Musk', 11, NULL, NULL);


-- Insert perfumes into the Perfume table for Mancera
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Gold Prestigium', 12, NULL, NULL),
('Pink Prestigium', 12, NULL, NULL),
('Aoud Caf', 12, NULL, NULL),
('The Aoud', 12, NULL, NULL),
('Aoud Blue Notes', 12, NULL, NULL),
('So Blue', 12, NULL, NULL),
('Aoud Orchid', 12, NULL, NULL),
('Choco Violet', 12, NULL, NULL),
('Coco Vanille', 12, NULL, NULL),
('Holidays', 12, NULL, NULL),
('Pearl', 12, NULL, NULL),
('Sicily', 12, NULL, NULL),
('Amber Roses', 12, NULL, NULL),
('Aoud Black Candy', 12, NULL, NULL),
('Aoud Vanille', 12, NULL, NULL),
('Indian Dream', 12, NULL, NULL),
('Roses Chocolate', 12, NULL, NULL),
('Roses Greedy', 12, NULL, NULL),
('Aoud S', 12, NULL, NULL),
('Black Intensive Aoud', 12, NULL, NULL),
('Black Prestigium', 12, NULL, NULL),
('Aoud Sandroses', 12, NULL, NULL),
('Black to Black', 12, NULL, NULL),
('Blue Aoud', 12, NULL, NULL),
('Aoud Line', 12, NULL, NULL),
('Black Line', 12, NULL, NULL),
('Lemon Line', 12, NULL, NULL),
('Aoud Lemon Mint', 12, NULL, NULL),
('Velvet Vanilla', 12, NULL, NULL),
('Aoud Violet', 12, NULL, NULL),
('Cedrat Boise', 12, NULL, NULL),
('Roses Vanille', 12, NULL, NULL),
('Sand Aoud', 12, NULL, NULL),
('Wind Wood', 12, NULL, NULL),
('Kumkat Wood', 12, NULL, NULL),
('Musk of Flowers', 12, NULL, NULL),
('Roseaoud Musk', 12, NULL, NULL),
('Roses Jasmine', 12, NULL, NULL),
('Wave Musk', 12, NULL, NULL),
('Wild Fruits', 12, NULL, NULL),
('Voyage en Arabie Black Intensive Aoud', 12, NULL, NULL),
('Voyage en Arabie Gold Intensive Aoud', 12, NULL, NULL),
('Voyage en Arabie Silver Intensive Aoud', 12, NULL, NULL),
('Wild Candy', 12, NULL, NULL),
('Wild Cherry', 12, NULL, NULL),
('Wild Leather', 12, NULL, NULL),
('Wild Rose Oud', 12, NULL, NULL);

-- Insert perfumes into the Perfume table for Parfums de Marly
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Akaster', 13, NULL, NULL),
('Athalia', 13, NULL, NULL),
('Byerley', 13, NULL, NULL),
('Carlisle', 13, NULL, NULL),
('Darcy', 13, NULL, NULL),
('Darley', 13, NULL, NULL),
('Galloway', 13, NULL, NULL),
('Godolphin', 13, NULL, NULL),
('Herod', 13, NULL, NULL),
('Ispazon', 13, NULL, NULL),
('Layton', 13, NULL, NULL),
('Lippizan', 13, NULL, NULL),
('Meliora', 13, NULL, NULL),
('Nisean', 13, NULL, NULL),
('Pegasus', 13, NULL, NULL),
('Safanad', 13, NULL, NULL),
('Sedbury', 13, NULL, NULL),
('Shagya', 13, NULL, NULL),
('Tolla Pegasus', 13, NULL, NULL),
('Habdan', 13, NULL, NULL),
('Hamdani', 13, NULL, NULL),
('Kuhuyan', 13, NULL, NULL),
('Oajan', 13, NULL, NULL);

-- Insert perfumes into the Perfume table for Tom Ford
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Grey Vetiver', 14, NULL, NULL),
('Grey Vetiver Eau de Toilette', 14, NULL, NULL),
('Noir', 14, NULL, NULL),
('Noir Eau de Toilette', 14, NULL, NULL),
('Noir Extreme', 14, NULL, NULL),
('Noir Pour Femme', 14, NULL, NULL),
('Sahara Noir', 14, NULL, NULL),
('Tom Ford for Men', 14, NULL, NULL),
('Tom Ford for Men Extreme', 14, NULL, NULL),
('Violet Blonde', 14, NULL, NULL),
('White Patchouli', 14, NULL, NULL),
('Black Orchid', 14, NULL, NULL),
('Black Orchid Eau de Toilette', 14, NULL, NULL),
('Black Orchid Oud', 14, NULL, NULL),
('Black Orchid Perfume Lalique Edition', 14, NULL, NULL),
('Black Orchid Voile de Fleur', 14, NULL, NULL),
('Orchid Soleil', 14, NULL, NULL),
('Velvet Orchid', 14, NULL, NULL),
('Velvet Orchid Lumiere', 14, NULL, NULL),
('Cafe Rose', 14, NULL, NULL),
('Jonquille de Nuit', 14, NULL, NULL),
('Lys Fume', 14, NULL, NULL),
('Ombre de Hyacinth', 14, NULL, NULL),
('Amber Absolute', 14, NULL, NULL),
('Arabian Wood', 14, NULL, NULL),
('Azure Lime', 14, NULL, NULL),
('Black Violet', 14, NULL, NULL),
('Bois Marocain', 14, NULL, NULL),
('Bois Rouge', 14, NULL, NULL),
('Champaca Absolute', 14, NULL, NULL),
('Italian Cypress', 14, NULL, NULL),
('Japon Noir', 14, NULL, NULL),
('Jasmin Rouge', 14, NULL, NULL),
('Lavender Palm', 14, NULL, NULL),
('London', 14, NULL, NULL),
('Moss Breches', 14, NULL, NULL),
('Noir de Noir', 14, NULL, NULL),
('Ombre Leather 16', 14, NULL, NULL),
('Oud Fleur', 14, NULL, NULL),
('Oud Wood', 14, NULL, NULL),
('Patchouli Absolu', 14, NULL, NULL),
('Purple Patchouli', 14, NULL, NULL),
('Santal Blush', 14, NULL, NULL),
('Soleil Blanc', 14, NULL, NULL),
('Tobacco Oud', 14, NULL, NULL),
('Tobacco Vanille', 14, NULL, NULL),
('Tuscan Leather', 14, NULL, NULL),
('Velvet Gardenia', 14, NULL, NULL),
('Venetian Bergamot', 14, NULL, NULL),
('Atelier d Orient Shanghai Lily', 14, NULL, NULL),
('Atelier d Orient Fleur de Chine', 14, NULL, NULL),
('Atelier d Orient Plum Japonais', 14, NULL, NULL),
('Atelier d Orient Rive d Ambre', 14, NULL, NULL),
('Vert Boheme', 14, NULL, NULL),
('Vert d Encens', 14, NULL, NULL),
('Vert de Fleur', 14, NULL, NULL),
('Vert des Bois', 14, NULL, NULL),
('Costa Azzurra', 14, NULL, NULL),
('Fleur de Portofino', 14, NULL, NULL),
('Mandarino di Amalfi', 14, NULL, NULL),
('Neroli Portofino', 14, NULL, NULL),
('Neroli Portofino Acqua', 14, NULL, NULL),
('Neroli Portofino Forte', 14, NULL, NULL),
('White Musk Collection Jasmine Musk', 14, NULL, NULL),
('White Musk Collection Musk Pure', 14, NULL, NULL),
('White Musk Collection Urban Musk', 14, NULL, NULL),
('White Musk Collection White Suede', 14, NULL, NULL);

-- Insert perfumes into the Perfume table for Valentino
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Valentino', 15, NULL, NULL),
('Valentino Eau de Parfum', 15, NULL, NULL),
('Valentino Gold', 15, NULL, NULL),
('Rock n Dreams', 15, NULL, NULL),
('Rock n Rose', 15, NULL, NULL),
('Rock n Rose Pret A Porter', 15, NULL, NULL),
('Rock n Rose Couture', 15, NULL, NULL),
('V', 15, NULL, NULL),
('V Absolu', 15, NULL, NULL),
('V Ete', 15, NULL, NULL),
('V pour Homme', 15, NULL, NULL),
('Valentina', 15, NULL, NULL),
('Valentina Acqua Floreale', 15, NULL, NULL),
('Valentina Assoluto', 15, NULL, NULL),
('Valentina Myrrh Assoluto', 15, NULL, NULL),
('Valentina Oud Assoluto', 15, NULL, NULL),
('Valentina Pink', 15, NULL, NULL),
('Valentina Poudre', 15, NULL, NULL),
('Valentina Rosa Assoluto', 15, NULL, NULL),
('Valentino Donna', 15, NULL, NULL),
('Valentino Uomo', 15, NULL, NULL),
('Valentino Uomo 2015', 15, NULL, NULL),
('Valentino Uomo Intense', 15, NULL, NULL),
('Vendetta Donna', 15, NULL, NULL),
('Vendetta Uomo', 15, NULL, NULL),
('Very Valentino', 15, NULL, NULL),
('Very Valentino for Men', 15, NULL, NULL);

-- Insert perfumes into the Perfume table
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Begum', 16, NULL, NULL),
('Harrods Emerald Star', 16, NULL, NULL),
('Wabar', 16, NULL, NULL),
('Pikovaya Dama', 16, NULL, NULL),
('1888', 16, NULL, NULL),
('Bouquet Ideale', 16, NULL, NULL),
('Dama Bianca', 16, NULL, NULL),
('Dolce Amalfi', 16, NULL, NULL),
('Fiero', 16, NULL, NULL),
('Fiore d Ulivo', 16, NULL, NULL),
('Gran Ballo', 16, NULL, NULL),
('Italica', 16, NULL, NULL),
('La Tosca', 16, NULL, NULL),
('Lira', 16, NULL, NULL),
('Mefisto', 16, NULL, NULL),
('Regio', 16, NULL, NULL),
('40 Knots', 16, NULL, NULL),
('Ascot Moon', 16, NULL, NULL),
('Birdie', 16, NULL, NULL),
('Comandante', 16, NULL, NULL),
('Don', 16, NULL, NULL),
('Fatal Charme', 16, NULL, NULL),
('Ivory Route', 16, NULL, NULL),
('Kind of Blue', 16, NULL, NULL),
('Marquee', 16, NULL, NULL),
('More Than Words', 16, NULL, NULL),
('Shunkoin', 16, NULL, NULL),
('Black Sukar', 16, NULL, NULL),
('Java Blossom', 16, NULL, NULL),
('Kampuchea Noir', 16, NULL, NULL),
('King Masarat', 16, NULL, NULL),
('Oud Luban', 16, NULL, NULL),
('Warda Al Oud', 16, NULL, NULL),
('Al Khat', 16, NULL, NULL),
('Alexandria II', 16, NULL, NULL),
('Fars', 16, NULL, NULL),
('Gao', 16, NULL, NULL),
('Indochine', 16, NULL, NULL),
('Malesia', 16, NULL, NULL),
('Mamluk', 16, NULL, NULL),
('Zafar', 16, NULL, NULL),
('Zanzibar Najaf', 16, NULL, NULL),
('Amber Star', 16, NULL, NULL),
('Blue Hope', 16, NULL, NULL),
('Cruz del Sur', 16, NULL, NULL),
('Dhajala', 16, NULL, NULL),
('Dhofar', 16, NULL, NULL),
('Esquel', 16, NULL, NULL),
('Ibitira', 16, NULL, NULL),
('Kobe', 16, NULL, NULL),
('Lua', 16, NULL, NULL),
('Modoc', 16, NULL, NULL),
('Nio', 16, NULL, NULL),
('Oesel', 16, NULL, NULL),
('Oroville', 16, NULL, NULL),
('Red Hoba', 16, NULL, NULL),
('Shingl', 16, NULL, NULL),
('Star Musk', 16, NULL, NULL),
('Uden', 16, NULL, NULL),
('Damarose', 16, NULL, NULL),
('Elle', 16, NULL, NULL),
('Homme', 16, NULL, NULL),
('Irisss', 16, NULL, NULL),
('Richwood', 16, NULL, NULL),
('Symphonium', 16, NULL, NULL),
('XXY', 16, NULL, NULL),
('XJ 1861 Naxos', 16, NULL, NULL),
('XJ 1861 Renaissance', 16, NULL, NULL),
('XJ 1861 Zefiro', 16, NULL, NULL);

-- Insert perfumes into the Perfume table
INSERT INTO Perfume (perfume_name, brand_id, lenglevity, sillage) VALUES
('Eau Libre', 17, NULL, NULL),
('Saharienne', 17, NULL, NULL),
('Vice Versa', 17, NULL, NULL),
('Y', 17, NULL, NULL),
('Baby Doll', 17, NULL, NULL),
('Baby Doll Candy Pink', 17, NULL, NULL),
('Baby Doll Honeymoon Limited Edition', 17, NULL, NULL),
('Baby Doll Lucky Game', 17, NULL, NULL),
('Baby Doll Magic', 17, NULL, NULL),
('Baby Doll Music Box Collector 2007', 17, NULL, NULL),
('Baiser de Cinema', 17, NULL, NULL),
('Cinema', 17, NULL, NULL),
('Cinema Festival', 17, NULL, NULL),
('Cinema Festival d Ete', 17, NULL, NULL),
('Cinema Gold', 17, NULL, NULL),
('Cinema Scenario d Ete', 17, NULL, NULL),
('Elle', 17, NULL, NULL),
('Elle Edition Collector', 17, NULL, NULL),
('Elle Intense Eau de Parfum', 17, NULL, NULL),
('Elle Limited Edition', 17, NULL, NULL),
('Elle Limited Edition 2011', 17, NULL, NULL),
('Elle Shocking Elle Eau de Toilette', 17, NULL, NULL),
('Elle Summer Fragrance 2008', 17, NULL, NULL),
('In Love Again', 17, NULL, NULL),
('In Love Again Edition Fleur De La Passion', 17, NULL, NULL),
('In Love Again Jasmin Etoile', 17, NULL, NULL),
('Jazz', 17, NULL, NULL),
('Jazz Prestige', 17, NULL, NULL),
('Live Jazz', 17, NULL, NULL),
('Body Kouros', 17, NULL, NULL),
('Kouros', 17, NULL, NULL),
('Kouros Cologne Sport', 17, NULL, NULL),
('Kouros Cologne Sport Eau d Ete Summer Fragrance', 17, NULL, NULL),
('Kouros Eau de Sport', 17, NULL, NULL),
('Kouros Eau de Toilette Tonique', 17, NULL, NULL),
('Kouros Eau d Ete 2002', 17, NULL, NULL),
('Kouros Eau d Ete 2005', 17, NULL, NULL),
('Kouros Eau d Ete 2006', 17, NULL, NULL),
('Kouros Energizing 2010', 17, NULL, NULL),
('Kouros Fraicheur', 17, NULL, NULL),
('Kouros Summer Edition 2008', 17, NULL, NULL),
('Kouros Tatoo', 17, NULL, NULL),
('Yves Saint Laurent Kouros Silver', 17, NULL, NULL),
('L Homme', 17, NULL, NULL),
('L Homme Eau d Et', 17, NULL, NULL),
('L Homme Libre', 17, NULL, NULL),
('L Homme Libre Cologne Tonic', 17, NULL, NULL),
('L Homme Parfum Intense', 17, NULL, NULL),
('L Homme Ultime', 17, NULL, NULL),
('La Nuit de L Homme Eau lectrique', 17, NULL, NULL),
('La Nuit de L Homme L Intense', 17, NULL, NULL),
('La Nuit de l Homme', 17, NULL, NULL),
('La Nuit de l Homme Frozen Cologne', 17, NULL, NULL),
('La Nuit de L Homme Le Parfum', 17, NULL, NULL),
('L Homme Eau d Ete', 17, NULL, NULL),
('L Homme Sport', 17, NULL, NULL),
('L Homme Yves Saint Laurent design by Jean Nouvel', 17, NULL, NULL),
('L Homme Cologne Gingembre', 17, NULL, NULL),
('La Collection In Love Again', 17, NULL, NULL),
('La Collection Jazz', 17, NULL, NULL),
('La Collection M7 Oud Absolu', 17, NULL, NULL),
('La Collection Nu', 17, NULL, NULL),
('La Collection Pour Homme', 17, NULL, NULL),
('La Collection Rive Gauche Pour Homme', 17, NULL, NULL),
('La Collection Y', 17, NULL, NULL),
('La Collection Yvresse', 17, NULL, NULL),
('Caban', 17, NULL, NULL),
('Caftan', 17, NULL, NULL),
('Trench', 17, NULL, NULL),
('Tuxedo', 17, NULL, NULL),
('Cuir', 17, NULL, NULL),
('Velours', 17, NULL, NULL),
('Vinyle', 17, NULL, NULL),
('M7', 17, NULL, NULL),
('M7 Fresh', 17, NULL, NULL),
('Manifesto', 17, NULL, NULL),
('Manifesto l Elixir', 17, NULL, NULL),
('Manifesto Le Parfum', 17, NULL, NULL),
('Manifesto L Eclat', 17, NULL, NULL),
('Mon Paris', 17, NULL, NULL),
('Mon Paris Sparkle Clash Edition', 17, NULL, NULL),
('Nu', 17, NULL, NULL),
('Nu Eau de Toilette', 17, NULL, NULL),
('Belle d Opium', 17, NULL, NULL),
('Belle d Opium Eau de Parfum clat', 17, NULL, NULL),
('Black Opium', 17, NULL, NULL),
('Black Opium Eau de Toilette', 17, NULL, NULL),
('Black Opium Floral Shock', 17, NULL, NULL),
('Black Opium Nuit Blanche', 17, NULL, NULL),
('Black Opium Sparkle Clash Limited Collector s Edition Eau de Parfum', 17, NULL, NULL),
('Black Opium Sparkle Clash Limited Collector s Edition Eau de Toilette', 17, NULL, NULL),
('Black Opium Swarovski Edition', 17, NULL, NULL),
('Black Opium Wild Edition', 17, NULL, NULL),
('Opium', 17, NULL, NULL),
('Opium Collector Edition 2008', 17, NULL, NULL),
('Opium Collector s Edition 2013', 17, NULL, NULL),
('Opium Collector s Edition 2014', 17, NULL, NULL),
('Opium Eau D ete Summer Fragrance', 17, NULL, NULL),
('Opium Eau D ete Summer Fragrance 2003', 17, NULL, NULL),
('Opium Eau D ete Summer Fragrance 2004', 17, NULL, NULL),
('Opium Elixir Voluptueux', 17, NULL, NULL),
('Opium Fleur de Shanghai', 17, NULL, NULL),
('Opium Fleur Imperiale', 17, NULL, NULL),
('Opium Fraicheur d Orient', 17, NULL, NULL),
('Opium L gendes de Chine eau de Parfum', 17, NULL, NULL),
('Opium Orchid e de Chine', 17, NULL, NULL),
('Opium Orient Extreme', 17, NULL, NULL),
('Opium Oriental Limited Edition', 17, NULL, NULL),
('Opium Parfum', 17, NULL, NULL),
('Opium Poesie de Chine pour Femme', 17, NULL, NULL),
('Opium Poesie de Chine pour Homme', 17, NULL, NULL),
('Opium Pour Homme', 17, NULL, NULL),
('Opium Pour Homme Eau d Orient', 17, NULL, NULL),
('Opium Pour Homme Eau d Orient 2007', 17, NULL, NULL),
('Opium Pour Homme Eau de Parfum', 17, NULL, NULL),
('Opium Rouge Fatal Collector s Edition 2015', 17, NULL, NULL),
('Opium Secret de Parfum', 17, NULL, NULL),
('Opium Vapeurs de Parfum', 17, NULL, NULL),
('Exquisite Musk', 17, NULL, NULL),
('Magnificent Blossom', 17, NULL, NULL),
('Majestic Rose', 17, NULL, NULL),
('Noble Leather', 17, NULL, NULL),
('Splendid Wood', 17, NULL, NULL),
('Supreme Bouquet', 17, NULL, NULL),
('Supreme Bouquet Luxury Edition', 17, NULL, NULL),
('Paris', 17, NULL, NULL),
('Paris Eau de Printemps', 17, NULL, NULL),
('Paris Jardins Romantiques', 17, NULL, NULL),
('Paris Nuit de Fete', 17, NULL, NULL),
('Paris Pont des Amours', 17, NULL, NULL),
('Paris Premieres Roses', 17, NULL, NULL),
('Paris Premieres Roses 2010', 17, NULL, NULL),
('Paris Premieres Roses 2011', 17, NULL, NULL),
('Paris Premieres Roses 2012', 17, NULL, NULL),
('Paris Premieres Roses 2013', 17, NULL, NULL),
('Paris Premieres Roses 2014', 17, NULL, NULL),
('Paris Premieres Roses 2015', 17, NULL, NULL),
('Paris Premieres Roses 2016', 17, NULL, NULL),
('Paris Rebel Collector', 17, NULL, NULL),
('Paris Roses des Bois', 17, NULL, NULL),
('Paris Roses des Vergers', 17, NULL, NULL),
('Paris Roses Enchantees', 17, NULL, NULL),
('YSL Paris L Edition Venini', 17, NULL, NULL),
('Parisienne', 17, NULL, NULL),
('Parisienne A L Extreme', 17, NULL, NULL),
('Parisienne Eau de Toilette', 17, NULL, NULL),
('Parisienne dition Singuli re', 17, NULL, NULL),
('Parisienne L Essentiel', 17, NULL, NULL),
('Parisienne L Eau', 17, NULL, NULL),
('Yves Saint Laurent Pour Homme', 17, NULL, NULL),
('Yves Saint Laurent Pour Homme Haute Concentration', 17, NULL, NULL),
('Rive Gauche', 17, NULL, NULL),
('Rive Gauche Fraicheur', 17, NULL, NULL),
('Rive Gauche Intense', 17, NULL, NULL),
('Rive Gauche Light', 17, NULL, NULL),
('Rive Gauche pour Homme', 17, NULL, NULL),
('Rive Gauche Pour Homme Intense', 17, NULL, NULL),
('Rive Gauche Pour Homme Light', 17, NULL, NULL),
('Young Sexy Lovely', 17, NULL, NULL),
('Young Sexy Lovely Collector Edition Radiant 2008', 17, NULL, NULL),
('Young Sexy Lovely Collector Intense 2007', 17, NULL, NULL),
('Young Sexy Lovely Couture Collection 2009', 17, NULL, NULL),
('Young Sexy Lovely Spring Summer Collection 2008', 17, NULL, NULL),
('Yvresse Champagne', 17, NULL, NULL),
('Yvresse Eau de Toilette Legere', 17, NULL, NULL);

-- Insert main accords
INSERT INTO Main_Accords (accord_name) VALUES
('citrus'),
('aromatic'),
('fresh spicy'),
('fresh'),
('woody'),
('rose'),
('white floral'),
('tuberose'),
('animalic'),
('musky'),
('powdery'),
('yellow floral'),
('earthy'),
('amber'),
('floral'),
('green'),
('balsamic'),
('smoky'),
('oud'),
('leather'),
('fruity');

